# Generated by Django 3.0.8 on 2020-07-05 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id_exame', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('virus', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'exame',
                'managed': True,
                'unique_together': {('tipo', 'virus')},
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=255, unique=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'perfil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('area_de_pesquisa', models.CharField(blank=True, max_length=255, null=True)),
                ('instituicao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_de_nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('login', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('senha', models.CharField(blank=True, max_length=255, null=True)),
                ('id_tutor', models.ForeignKey(blank=True, db_column='id_tutor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Pessoa')),
            ],
            options={
                'db_table': 'pessoa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('classe', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'servico',
                'managed': True,
                'unique_together': {('nome', 'classe')},
            },
        ),
        migrations.CreateModel(
            name='RegistroDeUso',
            fields=[
                ('id_registro_de_uso', models.AutoField(primary_key=True, serialize=False)),
                ('data_de_uso', models.DateTimeField()),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Perfil')),
                ('id_servico', models.ForeignKey(db_column='id_servico', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Servico')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Pessoa')),
            ],
            options={
                'db_table': 'registro_de_uso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tutelamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_inicio', models.DateField()),
                ('data_de_termino', models.DateField(blank=True, null=True)),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Perfil')),
                ('id_servico', models.ForeignKey(db_column='id_servico', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Servico')),
                ('id_tutor', models.ForeignKey(db_column='id_tutor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutor', to='main.Pessoa')),
                ('id_usuario_tutelado', models.ForeignKey(db_column='id_usuario_tutelado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutelado', to='main.Pessoa')),
            ],
            options={
                'db_table': 'tutelamento',
                'managed': True,
                'unique_together': {('id_usuario_tutelado', 'id_tutor', 'id_servico', 'id_perfil')},
            },
        ),
        migrations.CreateModel(
            name='Realiza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_amostra', models.CharField(blank=True, max_length=255, null=True)),
                ('data_de_realizacao', models.DateTimeField(blank=True, null=True)),
                ('data_de_solicitacao', models.DateTimeField(blank=True, null=True)),
                ('id_exame', models.ForeignKey(db_column='id_exame', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Exame')),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Pessoa')),
            ],
            options={
                'db_table': 'realiza',
                'managed': True,
                'unique_together': {('id_paciente', 'id_exame', 'data_de_realizacao')},
            },
        ),
        migrations.CreateModel(
            name='Possui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Perfil')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Pessoa')),
            ],
            options={
                'db_table': 'possui',
                'managed': True,
                'unique_together': {('id_usuario', 'id_perfil')},
            },
        ),
        migrations.CreateModel(
            name='Pertence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Perfil')),
                ('id_servico', models.ForeignKey(db_column='id_servico', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Servico')),
            ],
            options={
                'db_table': 'pertence',
                'managed': True,
                'unique_together': {('id_servico', 'id_perfil')},
            },
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_exame', models.ForeignKey(db_column='id_exame', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Exame')),
                ('id_servico', models.ForeignKey(db_column='id_servico', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Servico')),
            ],
            options={
                'db_table': 'gerencia',
                'managed': True,
                'unique_together': {('id_servico', 'id_exame')},
            },
        ),
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_amostra', models.CharField(max_length=255)),
                ('metodo_de_coleta', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('id_exame', models.ForeignKey(db_column='id_exame', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Exame')),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Pessoa')),
            ],
            options={
                'db_table': 'amostra',
                'managed': True,
                'unique_together': {('id_paciente', 'id_exame', 'codigo_amostra')},
            },
        ),
    ]
